[package]
name = "platform-event-store"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
sea-orm.workspace = true
tokio.workspace = true
tracing.workspace = true
serde.workspace = true
uuid.workspace = true
chrono.workspace = true
sha2.workspace = true
platform-error.workspace = true
platform-proto.workspace = true
