[package]
name = "iam-service"
version.workspace = true
edition.workspace = true

[dependencies]
shared-types.workspace = true
platform-error.workspace = true
platform-config.workspace = true
platform-logging.workspace = true
platform-db.workspace = true
platform-middleware.workspace = true
platform-messaging.workspace = true

tokio.workspace = true
axum.workspace = true
tower.workspace = true
tower-http.workspace = true
http.workspace = true
serde.workspace = true
serde_json.workspace = true
sea-orm.workspace = true
sea-orm-migration.workspace = true
uuid.workspace = true
chrono.workspace = true
tracing.workspace = true
thiserror.workspace = true
async-trait.workspace = true
argon2.workspace = true
jsonwebtoken.workspace = true
ipnet.workspace = true
redis.workspace = true
sha2.workspace = true
sha1 = "0.10"
hmac = "0.12"
async-nats.workspace = true
hex.workspace = true
rand = "0.8"
validator.workspace = true
url = "2"
