[package]
name = "outbox-relay"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
platform-registry.workspace = true
async-trait.workspace = true
tokio.workspace = true
tonic.workspace = true
sea-orm.workspace = true
tracing.workspace = true
serde.workspace = true
uuid.workspace = true
chrono.workspace = true
thiserror.workspace = true
futures.workspace = true
platform-proto.workspace = true
platform-logging.workspace = true
dotenvy.workspace = true
platform-error.workspace = true
platform-outbox.workspace = true
platform-messaging.workspace = true
platform-health.workspace = true

[dev-dependencies]
proptest.workspace = true
