[package]
name = "platform-clients"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
tokio.workspace = true
tonic.workspace = true
tracing.workspace = true
thiserror.workspace = true
futures.workspace = true
platform-proto.workspace = true
platform-config.workspace = true
uuid.workspace = true
