[package]
name = "outbox-relay"
version.workspace = true
edition.workspace = true

[dependencies]
platform-config.workspace = true
platform-db.workspace = true
platform-logging.workspace = true
platform-messaging.workspace = true
platform-error.workspace = true

tokio.workspace = true
tracing.workspace = true
sea-orm.workspace = true
