use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use uuid::Uuid;

/// An AML alert generated by the monitoring engine.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AmlAlert {
    pub alert_id: Uuid,
    pub operator_id: Uuid,
    pub transaction_id: Uuid,
    pub alert_type: AmlAlertType,
    pub severity: AlertSeverity,
    pub rule_id: String,
    pub details: String,
    pub status: AlertStatus,
    pub reviewed_by: Option<Uuid>,
    pub reviewed_at: Option<DateTime<Utc>>,
    pub created_at: DateTime<Utc>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum AmlAlertType {
    Structuring,
    Velocity,
    AmountAnomaly,
    RapidSuccession,
}

impl AmlAlertType {
    pub fn as_str(&self) -> &'static str {
        match self {
            Self::Structuring => "structuring",
            Self::Velocity => "velocity",
            Self::AmountAnomaly => "amount_anomaly",
            Self::RapidSuccession => "rapid_succession",
        }
    }

    #[allow(dead_code)]
    pub fn parse_str(s: &str) -> Option<Self> {
        match s {
            "structuring" => Some(Self::Structuring),
            "velocity" => Some(Self::Velocity),
            "amount_anomaly" => Some(Self::AmountAnomaly),
            "rapid_succession" => Some(Self::RapidSuccession),
            _ => None,
        }
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum AlertSeverity {
    Low,
    Medium,
    High,
    Critical,
}

impl AlertSeverity {
    pub fn as_str(&self) -> &'static str {
        match self {
            Self::Low => "low",
            Self::Medium => "medium",
            Self::High => "high",
            Self::Critical => "critical",
        }
    }

    #[allow(dead_code)]
    pub fn parse_str(s: &str) -> Option<Self> {
        match s {
            "low" => Some(Self::Low),
            "medium" => Some(Self::Medium),
            "high" => Some(Self::High),
            "critical" => Some(Self::Critical),
            _ => None,
        }
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum AlertStatus {
    Open,
    UnderReview,
    Escalated,
    Closed,
}

impl AlertStatus {
    pub fn as_str(&self) -> &'static str {
        match self {
            Self::Open => "open",
            Self::UnderReview => "under_review",
            Self::Escalated => "escalated",
            Self::Closed => "closed",
        }
    }

    #[allow(dead_code)]
    pub fn parse_str(s: &str) -> Option<Self> {
        match s {
            "open" => Some(Self::Open),
            "under_review" => Some(Self::UnderReview),
            "escalated" => Some(Self::Escalated),
            "closed" => Some(Self::Closed),
            _ => None,
        }
    }
}
