//! PDF invoice generator — renders invoices as PDF documents.
//!
//! Uses a simple HTML-to-PDF approach. In production, this would use
//! a headless browser (wkhtmltopdf, puppeteer) or a PDF library (printpdf, genpdf).

use crate::domain::aggregates::Invoice;
use platform_error::PlatformError;

/// Generate a PDF invoice from an Invoice aggregate.
pub fn generate_invoice_pdf(invoice: &Invoice) -> Result<Vec<u8>, PlatformError> {
    // Build HTML invoice
    let html = build_invoice_html(invoice);

    // In production, convert HTML to PDF using:
    // - wkhtmltopdf (command-line)
    // - printpdf (Rust crate)
    // - genpdf (Rust crate)
    // - Headless Chrome/Puppeteer via HTTP

    // For now, return the HTML as bytes (can be rendered by browsers)
    // A real implementation would use `printpdf` or similar
    Ok(html.into_bytes())
}

/// Build HTML representation of an invoice.
fn build_invoice_html(invoice: &Invoice) -> String {
    let line_items_html: String = invoice.line_items.iter().enumerate().map(|(i, item)| {
        let qty = item.quantity.unwrap_or(1);
        format!(
            "<tr><td>{}</td><td>{}</td><td>{}</td><td>{:.2}</td></tr>",
            i + 1,
            item.description,
            qty,
            item.amount_minor_units as f64 / 100.0
        )
    }).collect();

    format!(
        r#"<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <style>
        body {{ font-family: Arial, sans-serif; margin: 40px; }}
        .header {{ text-align: center; margin-bottom: 30px; }}
        .invoice-id {{ font-size: 24px; font-weight: bold; }}
        table {{ width: 100%; border-collapse: collapse; margin: 20px 0; }}
        th, td {{ border: 1px solid #ddd; padding: 8px; text-align: left; }}
        th {{ background-color: #f2f2f2; }}
        .total {{ font-size: 18px; font-weight: bold; text-align: right; margin-top: 20px; }}
        .footer {{ margin-top: 40px; font-size: 12px; color: #666; text-align: center; }}
    </style>
</head>
<body>
    <div class="header">
        <div class="invoice-id">INVOICE</div>
        <p><strong>Invoice ID:</strong> {}</p>
        <p><strong>Order Reference:</strong> {}</p>
        <p><strong>Status:</strong> {}</p>
        <p><strong>Due Date:</strong> {}</p>
    </div>

    <table>
        <thead>
            <tr><th>#</th><th>Description</th><th>Quantity</th><th>Amount</th></tr>
        </thead>
        <tbody>
            {}
        </tbody>
    </table>

    <div class="total">
        <p>Total: {:.2} {}</p>
        <p>Paid: {:.2} {}</p>
        <p>Outstanding: {:.2} {}</p>
    </div>

    <div class="footer">
        <p>Generated by Payment Platform</p>
        <p>Invoice ID: {}</p>
    </div>
</body>
</html>"#,
        invoice.invoice_id,
        invoice.order_reference,
        invoice.status.as_str(),
        invoice.due_date.format("%Y-%m-%d"),
        line_items_html,
        invoice.total_amount.amount_minor_units as f64 / 100.0,
        invoice.total_amount.currency.0,
        invoice.paid_amount.amount_minor_units as f64 / 100.0,
        invoice.paid_amount.currency.0,
        (invoice.total_amount.amount_minor_units - invoice.paid_amount.amount_minor_units) as f64 / 100.0,
        invoice.total_amount.currency.0,
        invoice.invoice_id,
    )
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::domain::value_objects::InvoiceLineItem;
    use uuid::Uuid;

    #[test]
    fn test_generate_invoice_pdf() {
        let invoice = Invoice::new(
            Uuid::now_v7(),
            "ORD-001".to_string(),
            vec![
                InvoiceLineItem {
                    description: "Product A".to_string(),
                    amount_minor_units: 5000,
                    quantity: Some(2),
                },
                InvoiceLineItem {
                    description: "Product B".to_string(),
                    amount_minor_units: 3000,
                    quantity: Some(1),
                },
            ],
            chrono::Utc::now() + chrono::Duration::days(30),
            Some("customer@example.com".to_string()),
        );

        let pdf = generate_invoice_pdf(&invoice).unwrap();
        assert!(!pdf.is_empty());
        let html = String::from_utf8(pdf).unwrap();
        assert!(html.contains("INVOICE"));
        assert!(html.contains("ORD-001"));
        assert!(html.contains("Product A"));
    }
}
