[package]
name = "platform-api"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
tonic.workspace = true
tokio.workspace = true
tracing.workspace = true
serde.workspace = true
uuid.workspace = true
platform-proto.workspace = true
platform-middleware.workspace = true
