[package]
name = "platform-registry"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
tokio.workspace = true
tracing.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
uuid.workspace = true
etcd-client = "0.14"
tonic.workspace = true
async-trait.workspace = true
platform-config.workspace = true
