[package]
name = "platform-health"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
tokio.workspace = true
tonic.workspace = true
tracing.workspace = true
serde.workspace = true
serde_json.workspace = true
sea-orm.workspace = true
redis.workspace = true
async-nats.workspace = true
platform-proto.workspace = true
platform-config.workspace = true
platform-registry.workspace = true
