use sea_orm_migration::prelude::*;

#[derive(DeriveMigrationName)]
pub struct Migration;

#[async_trait::async_trait]
impl MigrationTrait for Migration {
    async fn up(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        // SRS Part 5 §4: Append-only event store for event-sourced aggregates
        manager
            .create_table(
                Table::create()
                    .table(EventStore::Table)
                    .if_not_exists()
                    .col(
                        ColumnDef::new(EventStore::EventId)
                            .uuid()
                            .not_null()
                            .primary_key(),
                    )
                    .col(
                        ColumnDef::new(EventStore::AggregateType)
                            .string_len(64)
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(EventStore::AggregateId)
                            .uuid()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(EventStore::EventSequence)
                            .big_integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(EventStore::EventType)
                            .string_len(128)
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(EventStore::EventVersion)
                            .integer()
                            .not_null()
                            .default(1),
                    )
                    .col(
                        ColumnDef::new(EventStore::Payload)
                            .json()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(EventStore::OccurredAt)
                            .timestamp_with_time_zone()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(EventStore::ActorType)
                            .string_len(32)
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(EventStore::ActorId)
                            .uuid()
                            .null(),
                    )
                    .col(
                        ColumnDef::new(EventStore::CausationId)
                            .uuid()
                            .null(),
                    )
                    .col(
                        ColumnDef::new(EventStore::CorrelationId)
                            .uuid()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(EventStore::TraceContext)
                            .string_len(256)
                            .null(),
                    )
                    .col(
                        ColumnDef::new(EventStore::Signature)
                            .binary_len(32)
                            .null(),
                    )
                    // Composite primary key for optimistic concurrency
                    .index(
                        Index::create()
                            .name("pk_event_store_aggregate")
                            .col(EventStore::AggregateType)
                            .col(EventStore::AggregateId)
                            .col(EventStore::EventSequence)
                            .unique(),
                    )
                    // Query indexes
                    .index(
                        Index::create()
                            .name("idx_event_store_aggregate_id")
                            .col(EventStore::AggregateType)
                            .col(EventStore::AggregateId),
                    )
                    .index(
                        Index::create()
                            .name("idx_event_store_correlation")
                            .col(EventStore::CorrelationId),
                    )
                    .index(
                        Index::create()
                            .name("idx_event_store_occurred_at")
                            .col(EventStore::OccurredAt),
                    )
                    .to_owned(),
            )
            .await
    }

    async fn down(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        manager
            .drop_table(Table::drop().table(EventStore::Table).to_owned())
            .await
    }
}

#[derive(DeriveIden)]
enum EventStore {
    Table,
    EventId,
    AggregateType,
    AggregateId,
    EventSequence,
    EventType,
    EventVersion,
    Payload,
    OccurredAt,
    ActorType,
    ActorId,
    CausationId,
    CorrelationId,
    TraceContext,
    Signature,
}
